name: hackaburg_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.17.0
  auto_route: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.0.1
  build_runner: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
