name: language_partner
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  http: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/LaPa-logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/LaPa-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/LaPa-logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/LaPa-logo.png"


flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true

  flutter:
    assets:
      - assets/
      - assets/images/
      - assets/images/juergen.png
      - assets/images/kebab_menu.svg
      - assets/images/LaPa-logo.png
      - assets/images/laura_mueller.png

